apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo-frontend
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: 390844776196.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 390844776196.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: df3d63b2
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yml
- front-service-patch.yml
